export const SET_MOVIES = "MOVIES/SET_MOVIES";
export const START_LOADING = "MOVIES/START_LOADING";
export const END_LOADING = "MOVIES/END_LOADING";
export const SET_FAVORITE = "FAVORITES/SET_FAVORITE";
export const SET_FAVORITES = "FAVORITES/SET_FAVORITES";
